### PR TITLE
Adding option no-lmfit 

### PR DESCRIPTION
**Pull request by ismael-mendoza**
@burchat and me thought it would be a good idea to toggle off the lmfit usage in the package, since the fit analysis is not used much for other analysis and could potentially take a long time. I achieve this by adding an argument `no-lmfit` that can be passed in when running `simulate.py`. 

I tried to mimic the behavior of `no-hsm` when designing the argument, but not sure if something like `use-lmfit` would be better for this case.

### CODE REVIEW

**Comment by dkirkby** [comment]
You can choose the cmd-line logic independently of the code API.  For example, since we probably want to omit the lmfit by default:
```
parser.add_argument('--add-lmfit', action='store_true', help='Perform LMFIT fitting')
```
combined with:
```
analyzer = descwl.analysis.OverlapAnalyzer(survey,args.no_hsm,!args.add_lmfit)
```

**Comment by ismael-mendoza** [comment]
Good suggestion! I made the changes, is there anything you think we should do before merging?

**Comment by dkirkby** [comment]
Your code changes look good!  I noticed that you added the execute bit to `.gitignore` and all of the jupyter notebook files.  Was that intentional or do you know why it is happening?  I don't think this permission bit should be set on those files.

**Comment by ismael-mendoza** [comment]
I did not mean to change the permission bits of the .gitignore or the jupyter notebook files at all. I remember this happened before earlier, let me see if I can change them back.

**Comment by ismael-mendoza** [comment]
I believe I was able to change back the permission bit. Do you think we can merge now ?

**Comment by dkirkby** [comment]
The `.gitignore` file still has the wrong permissions.

**Comment by ismael-mendoza** [comment]
Ok so for some reason running `chmod 644 .gitignore` did not do the trick, so I had to delete the `.gitignore` and then add it back. I just commited this new `.gitignore` so I think it should be good. To makes sure I also ran: 

```
stat -f '%A %a %n' .gitignore
>>> 644 1492288562 
```

Thanks!, please let me know if this is not the case.

**Comment by dkirkby** [comment]
The changes tab on this PR is still showing:
```
notebooks/.gitignore 100644 → 100755
```
This might be relevant, despite the comment that the problem is now fixed:

http://stackoverflow.com/questions/9027584/how-to-change-the-file-mode-on-github

**Comment by ismael-mendoza** [comment]
I just noticed there is a different `.gitignore` inside the notebooks folder and I was forgetting to change that one. I checked the overall file changes and I believe the code is ready.

**Comment by ismael-mendoza** [comment]
Just noticed that doing, 

```
analyzer = descwl.analysis.OverlapAnalyzer(survey,args.no_hsm,!args.add_lmfit)
```
produces an error since `!args.add_lmfit` is not a valid python expression, instead I did: 
```
analyzer = descwl.analysis.OverlapAnalyzer(survey,args.no_hsm,not args.add_lmfit)
```

**Comment by dkirkby** [comment]
Good catch!  Merging now.

**Pull request merged**
