### PR TITLE
removed instance of pos attribute in analysis.py

### PR DESCRIPTION
**Pull request by ismael-mendoza**
Pull request to remove the pos attribute usage in WLD in order to make it compatible with the new (and old?) version of galsim.

### CODE REVIEW

**Comment by dkirkby** [comment]
This looks good to me.  Are there other similar changes to make before I merge?

**Comment by ismael-mendoza** [comment]
Thanks!, currently looking for others now... 
As of now, no other error but will probably have a conclusive answer by tomorrow.

**Comment by fjaviersanchez** [comment]
It worked for me using GalSim v1.6. Feel free to merge the changes.

**Comment by dkirkby** [comment]
Thanks for doing these checks @ismael2395 and @fjaviersanchez!  Merging now.

**Comment by ismael-mendoza** [comment]
Thanks David, I just finished rerunning all my tests and I found no other changes to make.

**Pull request merged**
