### PR TITLE
Updates to work with python3

### PR DESCRIPTION
**Pull request by dkirkby**
Various updates to print, except, import, iteritems, decode for python3.

Tested with anaconda + python 3.6.

It would great if someone could check if this still works with python 2.7.

### CODE REVIEW

**Comment by dkirkby** [comment]
I have updated the tutorial notebook and checked that all the commands listed there still work in py3, but the other notebook still need updating (mostly just print statements).

**Comment by fjaviersanchez** [comment]
I checked `simulate.py`, `fisher.py` and `display.py` and they all work with Python2.7 as well.

**Comment by dkirkby** [comment]
Thanks!  Any objections if I merge this now @sowmyakth @fjaviersanchez ?

**Comment by fjaviersanchez** [comment]
Looks good to me!

**Comment by sowmyakth** [comment]
Yup. Works fine

**Comment by dkirkby** [comment]
Thanks for checking.  Merged now.

**Pull request merged**
